### ISSUE TITLE
Crates using skeptic are recompiled no matter what

### ISSUE THREAD

**Issue by torkleyy** [budziq/rust-skeptic#25]
Even though I didn't modify anything, the crate gets recompiled. I don't think I'm the only one facing this issue: https://github.com/kvark/froggy/issues/26

**Comment by steveatinfincia** [comment]
Just noticed this as well, we have a Visual Studio project that includes several Rust/Cargo sub-projects. Each one uses a crate that depends on skeptic, so even though nothing has changed in the Rust code or the dependencies, it take a full minute for each of them to build before the main project can build+run during development.

Perhaps a quick fix for crates *using* skeptic would be to put it behind a default feature flag that can be disabled, though I'm not sure what the root cause is.

**Comment by bozaro** [comment]
Root cause: https://github.com/rust-lang/cargo/issues/4213
